apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-frontend
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app: todo-frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-chatbot.frontend.selectorLabels" . | nindent 4 }}
