replicaCount: 1

backend:
  image: todo-backend:test
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  initContainer:
    enabled: false

frontend:
  image: todo-frontend:test
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
